version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - book_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
    name: book_scraper_mongodb_data

networks:
  book_network:
    name: book_scraper_network
    driver: bridge
